FROM golang:1.12-alpine3.9 AS builder
RUN apk add -U git gcc musl-dev
WORKDIR /workdir
COPY go.mod go.sum ./
RUN go mod download
COPY service service
RUN go build ./service/main.go

FROM alpine:3.9
RUN apk add -U --no-cache ca-certificates && update-ca-certificates
COPY --from=builder /workdir/main /usr/local/bin/service
CMD ["/usr/local/bin/service"]
