FROM golang:1.12-alpine3.9 AS builder
RUN apk add -U git gcc musl-dev
WORKDIR /workdir
COPY go.mod go.sum ./
RUN go mod download
COPY sds sds
RUN go build ./sds/main.go

FROM alpine:3.9
RUN apk add -U --no-cache ca-certificates && update-ca-certificates
COPY --from=builder /workdir/main /usr/local/bin/sds
CMD ["/usr/local/bin/sds"]
